language: go

go:
- "1.15.x"

script: |
  echo "Build shuttle" &&
  go build &&
  ./shuttle run test

services:
- docker

deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux
