name: "Install Shuttle"
description: "Installs Lunar Shuttle"
runs:
  using: "composite"
  steps:
    - run: |
        set -e

        case "$(uname -m)" in
            arm64|aarch64) arch=arm64 ;;
            x86_64|amd64)  arch=amd64 ;;
            *) echo "Unsupported architecture: $(uname -m)" >&2; exit 1 ;;
        esac

        case "$(uname -s)" in
            Darwin) os=darwin ;;
            Linux)  os=linux ;;
            *) echo "Unsupported operating system: $(uname -s)" >&2; exit 1 ;;
        esac

        curl -fsSLo shuttle https://github.com/lunarway/shuttle/releases/latest/download/shuttle-$os-$arch
        chmod +x shuttle

        if [ "$os" == "darwin" ]; then
            mkdir -p "$HOME/bin"
            mv shuttle "$HOME/bin/shuttle"
            echo "$HOME/bin" >> $GITHUB_PATH
            export PATH="$HOME/bin:$PATH"
        else
            mv shuttle /usr/local/bin/shuttle
        fi

        shuttle version
      shell: bash
